### ISSUE TITLE
Detaching composition root of CustomComponent will fail if CustomComponent was injected with Vaadin-CDI's @ViewScoped.

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/cdi#126]
**Originally by @peterl1084**

---

Detaching injected custom component having table as composition root fails with Vaadin-CDI.

See attached stack trace

```
at com.vaadin.server.AbstractClientConnector.detach(AbstractClientConnector.java:612) [vaadin-server-7.3.1.jar:7.3.1]
    at com.vaadin.ui.AbstractComponent.detach(AbstractComponent.java:594) [vaadin-server-7.3.1.jar:7.3.1]
    at com.vaadin.ui.AbstractField.detach(AbstractField.java:1413) [vaadin-server-7.3.1.jar:7.3.1]
    at com.vaadin.ui.AbstractSelect.detach(AbstractSelect.java:1865) [vaadin-server-7.3.1.jar:7.3.1]
    at com.vaadin.ui.Table.detach(Table.java:4246) [vaadin-server-7.3.1.jar:7.3.1]
    at com.vaadin.server.AbstractClientConnector.detach(AbstractClientConnector.java:607) [vaadin-server-7.3.1.jar:7.3.1]
    at com.vaadin.ui.AbstractComponent.detach(AbstractComponent.java:594) [vaadin-server-7.3.1.jar:7.3.1]
    at com.xxxx.xxxxx.ui.view.debug.scheduler.ScheduledTimers$Proxy$_$$_WeldClientProxy.detach(Unknown Source) [classes:]
    at com.vaadin.server.AbstractClientConnector.detach(AbstractClientConnector.java:607) [vaadin-server-7.3.1.jar:7.3.1]
    at com.vaadin.ui.AbstractComponent.detach(AbstractComponent.java:594) [vaadin-server-7.3.1.jar:7.3.1]
    at com.vaadin.server.AbstractClientConnector.detach(AbstractClientConnector.java:607) [vaadin-server-7.3.1.jar:7.3.1]
    at com.vaadin.ui.AbstractComponent.detach(AbstractComponent.java:594) [vaadin-server-7.3.1.jar:7.3.1]
    at com.xxxx.xxxxxx.ui.view.debug.scheduler.SchedulerDebugView.detach(SchedulerDebugView.java:122) [classes:]
    at com.vaadin.ui.AbstractComponent.setParent(AbstractComponent.java:476) [vaadin-server-7.3.1.jar:7.3.1]
    at com.xxxx.xxxxxx.ui.view.debug.scheduler.SchedulerDebugView$Proxy$_$$_WeldClientProxy.setParent(Unknown Source) [classes:]
    at com.vaadin.ui.AbstractSingleComponentContainer.setContent(AbstractSingleComponentContainer.java:138) [vaadin-server-7.3.1.jar:7.3.1]
    at com.xxxxx.XXXXXViewDisplay.showView(XXXXXViewDisplay.java:74) [classes:]
    at com.xxxxx.XXXXXViewDisplay$Proxy$_$$_WeldClientProxy.showView(Unknown Source) [classes:]
    at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:568) [vaadin-server-7.3.1.jar:7.3.1]
```

Component being injected is as follows

```

  @ViewScoped
  public class MyTableComponent extends CustomComponent {
     ...
       private Table table = new Table(); 
     ...

       setCompositionRoot(table);
  }
```

and it's used normally in a @CDIView like this:

```
@Inject
private MyTableComponent myTable;
```

---

 Imported from https://dev.vaadin.com/ issue #14767

**Comment by pleku** [comment]
Old v7 issue which I'm note entirely sure if it was even fixed, but we'll probably never get to it due to other priorities - closing the issue.
