### ISSUE TITLE
Injecting custom components without producer/qualifier throws NPE

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/cdi#127]
**Originally by _manuelboehm_**

---

We injected custom-components in our vaadin-cdi-based application running on JBoss with vaadin-cdi alpha. After updating to beta, we got a NPE when trying to start the application in the browser.

Application-Server: JBoss EAP 6.3
Vaadin-CDI-Version: 1.0.0.beta1+
We reproduced the error with a vaadin-sample-application from the archetype. Following dependencies were added:

```
<dependency>
    <groupId>com.vaadin</groupId>
    <artifactId>vaadin-cdi</artifactId>
    <version>1.0.0.beta2</version>
</dependency>
<dependency>
    <groupId>org.jboss.spec</groupId>
    <artifactId>jboss-javaee-6.0</artifactId>
    <version>1.0.0.Final</version>
    <type>pom</type>
    <scope>provided</scope>
</dependency>
```

Maven-compiler-plugin java-version has been set to 1.7 (jdk7u67).
The example-project is attached. The Java-Classes are the following:

```
@Theme("mytheme")
@SuppressWarnings("serial")
@CDIUI("")
public class MyVaadinUI extends UI {_    This works/gives a correct exception while deploying
_    @Inject
//    private Label component;

    // This does not work and throws a NPE when trying to start the application
    @Inject
    // @MyComponentQualifier
    private MyComponent component;

    // HINT: this worked with cdi version before beta1

    @Override
    protected void init(VaadinRequest request) {
        setContent(component);
    }
}
```

```
@UIScoped
public class MyComponent extends CustomComponent {

    @PostConstruct
    private void init() {
        setCompositionRoot(new Label("Test"));
    }
}
```

The Exception thrown by the used code of the example when trying to start the application is the following:

```
14:45:52,592 SEVERE [com.vaadin.server.DefaultErrorHandler] (http-/127.0.0.1:8080-4) : java.lang.RuntimeException: java.lang.NullPointerException
    at org.jboss.weld.util.reflection.SecureReflectionAccess.runAsInstantiation(SecureReflectionAccess.java:186) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.util.reflection.SecureReflections.newInstance(SecureReflections.java:341) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.bean.proxy.ProxyFactory.create(ProxyFactory.java:237) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.bean.proxy.ClientProxyFactory.create(ClientProxyFactory.java:105) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.bean.proxy.ClientProxyProvider.createClientProxy(ClientProxyProvider.java:87) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.bean.proxy.ClientProxyProvider.access$000(ClientProxyProvider.java:43) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.bean.proxy.ClientProxyProvider$1.load(ClientProxyProvider.java:53) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.bean.proxy.ClientProxyProvider$1.load(ClientProxyProvider.java:46) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3589)
    at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2374)
    at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2337)
    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2252)
    at com.google.common.cache.LocalCache.get(LocalCache.java:3990)
    at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3994)
    at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4878)
    at org.jboss.weld.util.cache.LoadingCacheUtils.getCacheValue(LoadingCacheUtils.java:49) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.util.cache.LoadingCacheUtils.getCastCacheValue(LoadingCacheUtils.java:73) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.bean.proxy.ClientProxyProvider.getClientProxy(ClientProxyProvider.java:102) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:621) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:692) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.injection.FieldInjectionPoint.inject(FieldInjectionPoint.java:136) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.util.Beans.injectBoundFields(Beans.java:796) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.util.Beans.injectFieldsAndInitializers(Beans.java:805) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.bean.ManagedBean$ManagedBeanInjectionTarget$1$1.proceed(ManagedBean.java:165) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.injection.InjectionContextImpl.run(InjectionContextImpl.java:48) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.bean.ManagedBean$ManagedBeanInjectionTarget$1.work(ManagedBean.java:161) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.bean.ManagedBean$FixInjectionPoint.run(ManagedBean.java:135) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.bean.ManagedBean$ManagedBeanInjectionTarget.inject(ManagedBean.java:157) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.bean.ManagedBean.create(ManagedBean.java:297) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at com.vaadin.cdi.internal.UIContextual.create(UIContextual.java:85) [vaadin-cdi-1.0.0.beta2.jar:1.0.0.beta2]
    at org.apache.deltaspike.core.util.context.ContextualStorage.createContextualInstance(ContextualStorage.java:117) [deltaspike-core-api-1.0.1.jar:1.0.1]
    at org.apache.deltaspike.core.util.context.AbstractContext.get(AbstractContext.java:129) [deltaspike-core-api-1.0.1.jar:1.0.1]
    at com.vaadin.cdi.internal.AbstractVaadinContext.get(AbstractVaadinContext.java:154) [vaadin-cdi-1.0.0.beta2.jar:1.0.0.beta2]
    at org.jboss.weld.bean.proxy.ContextBeanInstance.getInstance(ContextBeanInstance.java:90) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:79) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at my.company.npe.MyVaadinUI$Proxy$_$$_WeldClientProxy.addDetachListener(MyVaadinUI$Proxy$_$$_WeldClientProxy.java) [classes:]
    at com.vaadin.cdi.CDIUIProvider.createInstance(CDIUIProvider.java:93) [vaadin-cdi-1.0.0.beta2.jar:1.0.0.beta2]
    at com.vaadin.server.communication.UIInitHandler.getBrowserDetailsUI(UIInitHandler.java:199) [vaadin-server-7.3.1.jar:7.3.1]
    at com.vaadin.server.communication.UIInitHandler.synchronizedHandleRequest(UIInitHandler.java:74) [vaadin-server-7.3.1.jar:7.3.1]
    at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41) [vaadin-server-7.3.1.jar:7.3.1]
    at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1402) [vaadin-server-7.3.1.jar:7.3.1]
    at com.vaadin.cdi.internal.VaadinCDIServletService.handleRequest(VaadinCDIServletService.java:82) [vaadin-cdi-1.0.0.beta2.jar:1.0.0.beta2]
    at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:305) [vaadin-server-7.3.1.jar:7.3.1]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:847) [jboss-servlet-api_3.0_spec-1.0.2.Final-redhat-1.jar:1.0.2.Final-redhat-1]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:295) [jbossweb-7.4.8.Final-redhat-4.jar:7.4.8.Final-redhat-4]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.4.8.Final-redhat-4.jar:7.4.8.Final-redhat-4]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:231) [jbossweb-7.4.8.Final-redhat-4.jar:7.4.8.Final-redhat-4]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:149) [jbossweb-7.4.8.Final-redhat-4.jar:7.4.8.Final-redhat-4]
    at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:169) [jboss-as-web-7.4.0.Final-redhat-19.jar:7.4.0.Final-redhat-19]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:145) [jbossweb-7.4.8.Final-redhat-4.jar:7.4.8.Final-redhat-4]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:97) [jbossweb-7.4.8.Final-redhat-4.jar:7.4.8.Final-redhat-4]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:102) [jbossweb-7.4.8.Final-redhat-4.jar:7.4.8.Final-redhat-4]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344) [jbossweb-7.4.8.Final-redhat-4.jar:7.4.8.Final-redhat-4]
    at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:856) [jbossweb-7.4.8.Final-redhat-4.jar:7.4.8.Final-redhat-4]
    at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:653) [jbossweb-7.4.8.Final-redhat-4.jar:7.4.8.Final-redhat-4]
    at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:926) [jbossweb-7.4.8.Final-redhat-4.jar:7.4.8.Final-redhat-4]
    at java.lang.Thread.run(Thread.java:724) [rt.jar:1.7.0_25]
Caused by: java.lang.NullPointerException
    at my.company.npe.MyComponent$Proxy$_$$_WeldClientProxy.getParent(MyComponent$Proxy$_$$_WeldClientProxy.java) [classes:]
    at com.vaadin.server.AbstractClientConnector.getUI(AbstractClientConnector.java:446) [vaadin-server-7.3.1.jar:7.3.1]
    at my.company.npe.MyComponent$Proxy$_$$_WeldClientProxy.getUI(MyComponent$Proxy$_$$_WeldClientProxy.java) [classes:]
    at com.vaadin.server.AbstractClientConnector.markAsDirty(AbstractClientConnector.java:138) [vaadin-server-7.3.1.jar:7.3.1]
    at my.company.npe.MyComponent$Proxy$_$$_WeldClientProxy.markAsDirty(MyComponent$Proxy$_$$_WeldClientProxy.java) [classes:]
    at com.vaadin.ui.AbstractComponent.setWidth(AbstractComponent.java:865) [vaadin-server-7.3.1.jar:7.3.1]
    at my.company.npe.MyComponent$Proxy$_$$_WeldClientProxy.setWidth(MyComponent$Proxy$_$$_WeldClientProxy.java) [classes:]
    at com.vaadin.ui.CustomComponent.<init>(CustomComponent.java:73) [vaadin-server-7.3.1.jar:7.3.1]
    at my.company.npe.MyComponent.<init>(MyComponent.java:19) [classes:]
    at my.company.npe.MyComponent$Proxy$_$$_WeldClientProxy.<init>(MyComponent$Proxy$_$$_WeldClientProxy.java) [classes:]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [rt.jar:1.7.0_25]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) [rt.jar:1.7.0_25]
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [rt.jar:1.7.0_25]
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526) [rt.jar:1.7.0_25]
    at java.lang.Class.newInstance(Class.java:374) [rt.jar:1.7.0_25]
    at org.jboss.weld.util.reflection.SecureReflections$16.work(SecureReflections.java:344) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.util.reflection.SecureReflectionAccess.run(SecureReflectionAccess.java:52) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.util.reflection.SecureReflectionAccess.runAsInstantiation(SecureReflectionAccess.java:173) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    ... 56 more

14:45:52,670 ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/npe-1.0.0-SNAPSHOT].[VaadinServlet]] (http-/127.0.0.1:8080-4) JBWEB000236: Servlet.service() for servlet VaadinServlet threw exception: java.lang.NullPointerException
    at my.company.npe.MyComponent$Proxy$_$$_WeldClientProxy.getParent(MyComponent$Proxy$_$$_WeldClientProxy.java) [classes:]
    at com.vaadin.server.AbstractClientConnector.getUI(AbstractClientConnector.java:446) [vaadin-server-7.3.1.jar:7.3.1]
    at my.company.npe.MyComponent$Proxy$_$$_WeldClientProxy.getUI(MyComponent$Proxy$_$$_WeldClientProxy.java) [classes:]
    at com.vaadin.server.AbstractClientConnector.markAsDirty(AbstractClientConnector.java:138) [vaadin-server-7.3.1.jar:7.3.1]
    at my.company.npe.MyComponent$Proxy$_$$_WeldClientProxy.markAsDirty(MyComponent$Proxy$_$$_WeldClientProxy.java) [classes:]
    at com.vaadin.ui.AbstractComponent.setWidth(AbstractComponent.java:865) [vaadin-server-7.3.1.jar:7.3.1]
    at my.company.npe.MyComponent$Proxy$_$$_WeldClientProxy.setWidth(MyComponent$Proxy$_$$_WeldClientProxy.java) [classes:]
    at com.vaadin.ui.CustomComponent.<init>(CustomComponent.java:73) [vaadin-server-7.3.1.jar:7.3.1]
    at my.company.npe.MyComponent.<init>(MyComponent.java:19) [classes:]
    at my.company.npe.MyComponent$Proxy$_$$_WeldClientProxy.<init>(MyComponent$Proxy$_$$_WeldClientProxy.java) [classes:]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [rt.jar:1.7.0_25]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) [rt.jar:1.7.0_25]
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [rt.jar:1.7.0_25]
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526) [rt.jar:1.7.0_25]
    at java.lang.Class.newInstance(Class.java:374) [rt.jar:1.7.0_25]
    at org.jboss.weld.util.reflection.SecureReflections$16.work(SecureReflections.java:344) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.util.reflection.SecureReflectionAccess.run(SecureReflectionAccess.java:52) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.util.reflection.SecureReflectionAccess.runAsInstantiation(SecureReflectionAccess.java:173) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.util.reflection.SecureReflections.newInstance(SecureReflections.java:341) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.bean.proxy.ProxyFactory.create(ProxyFactory.java:237) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.bean.proxy.ClientProxyFactory.create(ClientProxyFactory.java:105) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.bean.proxy.ClientProxyProvider.createClientProxy(ClientProxyProvider.java:87) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.bean.proxy.ClientProxyProvider.access$000(ClientProxyProvider.java:43) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.bean.proxy.ClientProxyProvider$1.load(ClientProxyProvider.java:53) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.bean.proxy.ClientProxyProvider$1.load(ClientProxyProvider.java:46) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3589)
    at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2374)
    at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2337)
    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2252)
    at com.google.common.cache.LocalCache.get(LocalCache.java:3990)
    at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3994)
    at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4878)
    at org.jboss.weld.util.cache.LoadingCacheUtils.getCacheValue(LoadingCacheUtils.java:49) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.util.cache.LoadingCacheUtils.getCastCacheValue(LoadingCacheUtils.java:73) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.bean.proxy.ClientProxyProvider.getClientProxy(ClientProxyProvider.java:102) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:621) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:692) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.injection.FieldInjectionPoint.inject(FieldInjectionPoint.java:136) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.util.Beans.injectBoundFields(Beans.java:796) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.util.Beans.injectFieldsAndInitializers(Beans.java:805) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.bean.ManagedBean$ManagedBeanInjectionTarget$1$1.proceed(ManagedBean.java:165) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.injection.InjectionContextImpl.run(InjectionContextImpl.java:48) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.bean.ManagedBean$ManagedBeanInjectionTarget$1.work(ManagedBean.java:161) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.bean.ManagedBean$FixInjectionPoint.run(ManagedBean.java:135) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.bean.ManagedBean$ManagedBeanInjectionTarget.inject(ManagedBean.java:157) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.bean.ManagedBean.create(ManagedBean.java:297) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at com.vaadin.cdi.internal.UIContextual.create(UIContextual.java:85) [vaadin-cdi-1.0.0.beta2.jar:1.0.0.beta2]
    at org.apache.deltaspike.core.util.context.ContextualStorage.createContextualInstance(ContextualStorage.java:117) [deltaspike-core-api-1.0.1.jar:1.0.1]
    at org.apache.deltaspike.core.util.context.AbstractContext.get(AbstractContext.java:129) [deltaspike-core-api-1.0.1.jar:1.0.1]
    at com.vaadin.cdi.internal.AbstractVaadinContext.get(AbstractVaadinContext.java:154) [vaadin-cdi-1.0.0.beta2.jar:1.0.0.beta2]
    at org.jboss.weld.bean.proxy.ContextBeanInstance.getInstance(ContextBeanInstance.java:90) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:79) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at my.company.npe.MyVaadinUI$Proxy$_$$_WeldClientProxy.addDetachListener(MyVaadinUI$Proxy$_$$_WeldClientProxy.java) [classes:]
    at com.vaadin.cdi.CDIUIProvider.createInstance(CDIUIProvider.java:93) [vaadin-cdi-1.0.0.beta2.jar:1.0.0.beta2]
    at com.vaadin.server.communication.UIInitHandler.getBrowserDetailsUI(UIInitHandler.java:199) [vaadin-server-7.3.1.jar:7.3.1]
    at com.vaadin.server.communication.UIInitHandler.synchronizedHandleRequest(UIInitHandler.java:74) [vaadin-server-7.3.1.jar:7.3.1]
    at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41) [vaadin-server-7.3.1.jar:7.3.1]
    at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1402) [vaadin-server-7.3.1.jar:7.3.1]
    at com.vaadin.cdi.internal.VaadinCDIServletService.handleRequest(VaadinCDIServletService.java:82) [vaadin-cdi-1.0.0.beta2.jar:1.0.0.beta2]
    at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:305) [vaadin-server-7.3.1.jar:7.3.1]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:847) [jboss-servlet-api_3.0_spec-1.0.2.Final-redhat-1.jar:1.0.2.Final-redhat-1]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:295) [jbossweb-7.4.8.Final-redhat-4.jar:7.4.8.Final-redhat-4]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.4.8.Final-redhat-4.jar:7.4.8.Final-redhat-4]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:231) [jbossweb-7.4.8.Final-redhat-4.jar:7.4.8.Final-redhat-4]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:149) [jbossweb-7.4.8.Final-redhat-4.jar:7.4.8.Final-redhat-4]
    at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:169) [jboss-as-web-7.4.0.Final-redhat-19.jar:7.4.0.Final-redhat-19]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:145) [jbossweb-7.4.8.Final-redhat-4.jar:7.4.8.Final-redhat-4]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:97) [jbossweb-7.4.8.Final-redhat-4.jar:7.4.8.Final-redhat-4]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:102) [jbossweb-7.4.8.Final-redhat-4.jar:7.4.8.Final-redhat-4]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344) [jbossweb-7.4.8.Final-redhat-4.jar:7.4.8.Final-redhat-4]
    at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:856) [jbossweb-7.4.8.Final-redhat-4.jar:7.4.8.Final-redhat-4]
    at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:653) [jbossweb-7.4.8.Final-redhat-4.jar:7.4.8.Final-redhat-4]
    at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:926) [jbossweb-7.4.8.Final-redhat-4.jar:7.4.8.Final-redhat-4]
    at java.lang.Thread.run(Thread.java:724) [rt.jar:1.7.0_25]

```

The exception thrown by the commented version (e.g. when trying to inject a label) while trying to deploy is the following:

```
14:47:05,101 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-14) MSC000001: Failed to start service jboss.deployment.unit."npe-1.0.0-SNAPSHOT.war".WeldStartService: org.jboss.msc.service.StartException in service jboss.deployment.unit."npe-1.0.0-SNAPSHOT.war".WeldStartService: Failed to start service
    at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1936) [jboss-msc-1.1.5.Final-redhat-1.jar:1.1.5.Final-redhat-1]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [rt.jar:1.7.0_25]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [rt.jar:1.7.0_25]
    at java.lang.Thread.run(Thread.java:724) [rt.jar:1.7.0_25]
Caused by: org.jboss.weld.exceptions.DeploymentException: WELD-001408 Unsatisfied dependencies for type [Label] with qualifiers [@Default] at injection point [[field] @Inject private my.company.npe.MyVaadinUI.component]
    at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:315)
    at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:284)
    at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:147)
    at org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:167)
    at org.jboss.weld.bootstrap.Validator.validateBeans(Validator.java:386)
    at org.jboss.weld.bootstrap.Validator.validateDeployment(Validator.java:371)
    at org.jboss.weld.bootstrap.WeldBootstrap.validateBeans(WeldBootstrap.java:379)
    at org.jboss.as.weld.WeldStartService.start(WeldStartService.java:64)
    at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1980) [jboss-msc-1.1.5.Final-redhat-1.jar:1.1.5.Final-redhat-1]
    at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1913) [jboss-msc-1.1.5.Final-redhat-1.jar:1.1.5.Final-redhat-1]
    ... 3 more
```

HINT: Having a producer like in the attached example works for both injections.

In our opinion, there should be a proper exception instead of NPE.

---

 Imported from https://dev.vaadin.com/ issue #14770

**Comment by pleku** [comment]
Old issue which I'm note entirely sure if it was even fixed, but we'll probably never get to it due to other priorities - closing the issue. In case this still reproduces with v8, please open a new issue.
