### ISSUE TITLE
CDIViewProvider broken with websockets on Glassfish 4.1

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/cdi#143]
**Originally by @Legioth**

---

The tutorial project does not work on Glassfish with websockets. Changing to use long-polling makes the problems go away.

When logging in, the following exception is thrown:

```
java.lang.RuntimeException: java.lang.IllegalStateException: Singleton not set for org.glassfish.main.core.kernel [152]
        at com.vaadin.cdi.tutorial.NavigationServiceImpl.onNavigationEvent(NavigationServiceImpl.java:40)
        at com.vaadin.cdi.tutorial.NavigationServiceImpl$Proxy$_$$_WeldSubclass.onNavigationEvent(Unknown Source)
        at com.vaadin.cdi.tutorial.NavigationLogDecorator.onNavigationEvent(NavigationLogDecorator.java:25)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.jboss.weld.annotated.runtime.InvokableAnnotatedMethod.invokeOnInstance(InvokableAnnotatedMethod.java:85)
        at org.jboss.weld.bean.proxy.DecoratorProxyMethodHandler.doInvoke(DecoratorProxyMethodHandler.java:78)
        at org.jboss.weld.bean.proxy.DecoratorProxyMethodHandler.doInvoke(DecoratorProxyMethodHandler.java:67)
        at org.jboss.weld.interceptor.util.proxy.TargetInstanceProxyMethodHandler.invoke(TargetInstanceProxyMethodHandler.java:33)
        at org.jboss.weld.bean.proxy.TargetBeanInstance.invoke(TargetBeanInstance.java:91)
        at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:100)
        at com.vaadin.cdi.tutorial.NavigationServiceImpl$Proxy$_$$_Weld$Proxy$.onNavigationEvent(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.jboss.weld.util.reflection.Reflections.invokeAndUnwrap(Reflections.java:414)
        at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:58)
        at com.vaadin.cdi.tutorial.NavigationServiceImpl$Proxy$_$$_WeldSubclass.onNavigationEvent(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.jboss.weld.injection.MethodInjectionPoint.invokeOnInstanceWithSpecialValue(MethodInjectionPoint.java:90)
        at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:271)
        at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:258)
        at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:237)
        at org.jboss.weld.event.ObserverNotifier.notifyObserver(ObserverNotifier.java:174)
        at org.jboss.weld.event.ObserverNotifier.notifyObserver(ObserverNotifier.java:170)
        at org.jboss.weld.event.TransactionalObserverNotifier.notifyObserver(TransactionalObserverNotifier.java:46)
        at org.jboss.weld.event.ObserverNotifier.notifyObservers(ObserverNotifier.java:124)
        at org.jboss.weld.event.EventImpl.fire(EventImpl.java:84)
        at com.vaadin.cdi.tutorial.LoginView.buttonClick(LoginView.java:69)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508)
        at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:198)
        at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:161)
        at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:979)
        at com.vaadin.ui.Button.fireClick(Button.java:380)
        at com.vaadin.ui.Button.click(Button.java:369)
        at com.vaadin.ui.Button$ClickShortcut.handleAction(Button.java:548)
        at com.vaadin.event.ActionManager.handleAction(ActionManager.java:238)
        at com.vaadin.event.ActionManager.handleAction(ActionManager.java:238)
        at com.vaadin.event.ConnectorActionManager.handleAction(ConnectorActionManager.java:81)
        at com.vaadin.event.ActionManager.handleAction(ActionManager.java:233)
        at com.vaadin.event.ActionManager.handleActions(ActionManager.java:216)
        at com.vaadin.ui.UI.changeVariables(UI.java:361)
        at com.vaadin.server.communication.ServerRpcHandler.changeVariables(ServerRpcHandler.java:485)
        at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:301)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:565)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:545)
        at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.IllegalStateException: Singleton not set for org.glassfish.main.core.kernel [152]
        at org.jboss.weld.bootstrap.api.helpers.TCCLSingletonProvider$TCCLSingleton.get(TCCLSingletonProvider.java:54)
        at org.jboss.weld.Container.instance(Container.java:65)
        at org.jboss.weld.bean.proxy.ClientProxyProvider.createClientProxy(ClientProxyProvider.java:174)
        at org.jboss.weld.bean.proxy.ClientProxyProvider.createClientProxy(ClientProxyProvider.java:170)
        at org.jboss.weld.bean.proxy.ClientProxyProvider.access$100(ClientProxyProvider.java:45)
        at org.jboss.weld.bean.proxy.ClientProxyProvider$CreateClientProxy.load(ClientProxyProvider.java:56)
        at org.jboss.weld.bean.proxy.ClientProxyProvider$CreateClientProxy.load(ClientProxyProvider.java:52)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3589)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2374)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2337)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2252)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3990)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3994)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4878)
        at org.jboss.weld.util.cache.LoadingCacheUtils.getCacheValue(LoadingCacheUtils.java:49)
        at org.jboss.weld.util.cache.LoadingCacheUtils.getCastCacheValue(LoadingCacheUtils.java:74)
        at org.jboss.weld.bean.proxy.ClientProxyProvider.getClientProxy(ClientProxyProvider.java:204)
        at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:734)
        at org.jboss.weld.manager.BeanManagerImpl.getInjectableReference(BeanManagerImpl.java:831)
        at org.jboss.weld.injection.FieldInjectionPoint.inject(FieldInjectionPoint.java:92)
        at org.jboss.weld.util.Beans.injectBoundFields(Beans.java:365)
        at org.jboss.weld.util.Beans.injectFieldsAndInitializers(Beans.java:376)
        at org.jboss.weld.injection.producer.ResourceInjector$1.proceed(ResourceInjector.java:70)
        at org.glassfish.weld.services.InjectionServicesImpl.aroundInject(InjectionServicesImpl.java:124)
        at org.jboss.weld.injection.InjectionContextImpl.run(InjectionContextImpl.java:46)
        at org.jboss.weld.injection.producer.ResourceInjector.inject(ResourceInjector.java:65)
        at org.jboss.weld.injection.producer.BasicInjectionTarget.inject(BasicInjectionTarget.java:109)
        at org.jboss.weld.bean.ManagedBean.create(ManagedBean.java:150)
        at com.vaadin.cdi.internal.UIContextual.create(UIContextual.java:85)
        at org.apache.deltaspike.core.util.context.ContextualStorage.createContextualInstance(ContextualStorage.java:117)
        at org.apache.deltaspike.core.util.context.AbstractContext.get(AbstractContext.java:129)
        at com.vaadin.cdi.internal.AbstractVaadinContext.get(AbstractVaadinContext.java:156)
        at com.vaadin.cdi.internal.ContextWrapper.get(ContextWrapper.java:49)
        at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:740)
        at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:760)
        at org.jboss.weld.util.ForwardingBeanManager.getReference(ForwardingBeanManager.java:61)
        at org.jboss.weld.bean.builtin.BeanManagerProxy.getReference(BeanManagerProxy.java:78)
        at com.vaadin.cdi.CDIViewProvider.getView(CDIViewProvider.java:286)
        at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:512)
        at com.vaadin.cdi.tutorial.NavigationServiceImpl.onNavigationEvent(NavigationServiceImpl.java:36)
        ... 85 more
```

---

 Imported from https://dev.vaadin.com/ issue #15244

**Comment by pleku** [comment]
Old v7 issue which I think applies to v8 too, but we'll probably never get to it due to other priorities - closing the issue.
In case the is an issue for v7 extended support users or v8 users, please open a new issue with exact steps to reproduce.
