### ISSUE TITLE
NullPointerException in CDIViewProvider.getParameters

### ISSUE THREAD

**Issue by lubomirmatus** [vaadin/cdi#254]
I'm trying to upgrade from vaadin-cdi 2.0.0 to vaadin-cdi 3. I'm using vaadin-cdi 3.0.1 (issue also in 3.0.0) and I'm running into NullPointerException in CDIProvider.getParameters method at line 237. The 'lastViewAndParameters' member is null so then 'lastViewAndParameters.startsWith(viewName)' is throwing the exception.

MyUI.init() {
...
MainView mainView = (MainView) viewProvider.getView(MainView.VIEWNAME); // <-- exception inside
setContent(mainView);
...
}

This has been working fine in vaadin-cdi 2.0.0.

Stack trace:
júl 18, 2018 12:56:39 PM com.vaadin.server.DefaultErrorHandler doDefault
SEVERE: 
java.lang.NullPointerException
	at com.vaadin.cdi.CDIViewProvider.getParameters(CDIViewProvider.java:237)
	at com.vaadin.cdi.CDIViewProvider.getView(CDIViewProvider.java:225)
	at com.my.myui.MyUI.init(MyUI.java:193)
	at com.vaadin.ui.UI.doInit(UI.java:771)
	at com.vaadin.server.communication.UIInitHandler.getBrowserDetailsUI(UIInitHandler.java:218)
	at com.vaadin.server.communication.UIInitHandler.synchronizedHandleRequest(UIInitHandler.java:76)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1601)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:445)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.openejb.server.httpd.EEFilter.doFilter(EEFilter.java:65)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.tomee.catalina.OpenEJBValve.invoke(OpenEJBValve.java:44)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.tomee.catalina.OpenEJBSecurityListener$RequestCapturer.invoke(OpenEJBSecurityListener.java:97)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Unknown Source)

**Comment by kumm** [comment]
You should not need a ViewProvider at all.
Just `@Inject` your MainView. ( And do not forget to migrate to `CDINavigator` )

**Comment by kumm** [comment]
Sorry, I've missed we are in init.
During page load a view context is activated only after UI is navigated to the requested view. It is done by Vaadin framework after `UI.init`. So `ContextNotActiveException` exception is ok.

Your use case seems strange to me. Even if `@Inject` works `ManView` bean is destroyed on the first view navigation.

**Comment by lubomirmatus** [comment]
The code crashes before entering MyUi.init() method, probably on injecting MainView into MyUI.
So ... how to make it work ?
