### ISSUE TITLE
CDI is broken because tests are failing

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/cdi#288]
Follow up #286 
Checkout branch `flow-2`.
It has compilation errors because of #286.
There is a PR for it already. But this PR fails tests.

The reason is : CDI is broken apart from `createComponent` implementation absence.
Fix `createComponent` issue via adding this method and return back its old impl: just delegate to `getOrCreate(componentClass)`.
Now the source code is identical to the state before API change in Flow.

But CDI build fails with a number of test failures.
E.g.:
```
javax.enterprise.context.ContextNotActiveException: WebBeans context with scope type annotation @VaadinServiceScoped does not exist within current thread	at org.apache.webbeans.container.BeanManagerImpl.getContext(BeanManagerImpl.java:304)	at org.apache.webbeans.intercept.NormalScopedBeanInterceptorHandler.getContextualInstance(NormalScopedBeanInterceptorHandler.java:89)	at org.apache.webbeans.intercept.NormalScopedBeanInterceptorHandler.get(NormalScopedBeanInterceptorHandler.java:71)	at com.vaadin.cdi.CdiInstantiator$$OwbNormalScopeProxy0.getDependencyFilters(com/vaadin/cdi/CdiInstantiator.java)	at com.vaadin.flow.server.VaadinService.init(VaadinService.java:275)	at com.vaadin.cdi.CdiVaadinServletService.init(CdiVaadinServletService.java:128)	at com.vaadin.cdi.CdiVaadinServletServiceTest.initService(CdiVaadinServletServiceTest.java:144)	at com.vaadin.cdi.CdiVaadinServletServiceTest.getInstantiator_serviceInitialized_cdiInstantiatorReturned(CdiVaadinServletServiceTest.java:82)	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)	at java.lang.reflect.Method.invoke(Method.java:498)	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)	at org.apache.deltaspike.testcontrol.api.junit.CdiTestRunner$ContainerAwareMethodInvoker.invokeMethod(CdiTestRunner.java:346)	at org.apache.deltaspike.testcontrol.api.junit.CdiTestRunner$ContainerAwareMethodInvoker.evaluate(CdiTestRunner.java:318)	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)	at org.apache.deltaspike.testcontrol.api.junit.CdiTestRunner.runChild(CdiTestRunner.java:177)	at org.apache.deltaspike.testcontrol.api.junit.CdiTestRunner.runChild(CdiTestRunner.java:76)	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)	at org.apache.deltaspike.testcontrol.api.junit.CdiTestRunner$BeforeClassStatement.evaluate(CdiTestRunner.java:372)	at org.apache.deltaspike.testcontrol.api.junit.CdiTestRunner$AfterClassStatement.evaluate(CdiTestRunner.java:393)	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)	at org.apache.deltaspike.testcontrol.api.junit.CdiTestRunner.run(CdiTestRunner.java:144)	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)	at java.lang.reflect.Method.invoke(Method.java:498)	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75) 
```

**Comment by denis-anisimov** [comment]
The reason of this behavior is a new code introduced in Flow at some point:
https://github.com/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java#L263-L266

This code resets the vaadin service thread local instance to `null`. Not sure how it had been set previously (before the changes) but now it's definitely `null`  on the call `instantiator.getDependencyFilters` which causes the failure.
Looks like this should be fixed in Flow.

**Comment by denis-anisimov** [comment]
Should be fixed by https://github.com/vaadin/flow/pull/5546 in Flow.
